### ISSUE TITLE
Feature Request. Untie deployment namespaces from the directory structure.

### ISSUE THREAD

**Issue by timuckun** [railsware/caphub#1]
I would like to consolidate my deployment files instead of creating a directory structure for every app and every configuation

My reasoning are
1. I don't like having a lot of files with the same name in the same project. So for example if I have ten projects I will have ten production.rb, ten staging.rb etc.
2. Most files only have one maybe two lines of code in them, it seems like overkill.

I would like the option to either create one master file for all apps  or one file per app or both.  All that has to be done is to introduce a way to inject the deployment namespace into capistrano. I am not familiar with it so maybe that's not a trivial task but I would like to put it in as a feature request.

Maybe the syntax could look like this

deploy :application do
        task :production do
             blah
        end
end

or this

deploy application:staging do
      blah
end

**Comment by ayanko** [comment]
It seems in this case you don't need **dynamic** configurations - capistrano-multiconfig.

Comment it out in `Gemfile`  and remove it from `config/deploy.rb` 

It's easy to write own **static** configuration implementation using pure capistrano:

Put into bottom of `config/deploy.rb`

<pre>
load 'config/deploy/blog.rb'
load 'config/deploy/wiki.rb'
...
</pre>


put into `config/deploy/blog.rb`

<pre>

namespace :blog do
  task :shared do
    set :application 'blog'
    # set another common options for blog
  end

  task :production do
    top.blog.shared

    set :environment, 'production'
    server 'blog.example.com', :app
    ...
  end

   task :staging do
     top.blog.shared

     set :environment, 'staging'
     server 'stage-blog.example.com', :app
     ...
   end

  task :another... do
    ...
  end

end
</pre>


etc ...

and use as usual:

```
$ cap blog:staging deploy:setup
```

And remember that CapHub is only _concept_. This gem only generate layout for capistrano and include useful gem.
if you want more - you include more capistrano gems/recipes/ etc.
If you want less - you just exclude unused gems.

The core is `capistrano-muliconfig` gem but caphub will of course works without it also.
You can replace it with another gem or just own implementation of configuration tasks.
Concept is simple:

```
$ cap CONFIGURATION_TASK ACTION_TASK1 ACTION_TASK2 ...
```

So it can't be feature request.

**Comment by timuckun** [comment]
OK great. I will give that a go...

Cheers.

On Sun, Jan 8, 2012 at 2:08 AM, Andriy Yanko
reply@reply.github.com
wrote:
