### ISSUE TITLE
Gem doesn't generate Capistrano 2 layout

### ISSUE THREAD

**Issue by sigfrid** [railsware/caphub#10]
I have tried to create a Capistrano 2 layout in Ruby 2.1.0, 2.0.0-p247 and 1.9.3-p327 by running `caphub --cap 2 mydeploy` but in both cases I get respectively:

`.rbenv/versions/2.1.0/lib/ruby/2.1.0/fileutils.rb:1573:in `stat': No such file or directory @ rb_file_s_stat`

`.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/fileutils.rb:1551:in `stat': No such file or directory`

`.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/fileutils.rb:1515:in `stat': No such file or directory`

Is Capistrano 2 still supported on CapHub 0.1.3?

**Comment by ayanko** [comment]
Try version 0.1.4
