### ISSUE TITLE
Different requires for different deploy applications

### ISSUE THREAD

**Issue by Fabs** [railsware/caphub#12]
I am using caphub to deploy one angular.js app and another rails app after i set up my machine with chef. 

My problem is that the require 'capistrano/bundle' for instance makes my angular.js fail because there are no Gemfile. So I need to require different recipes deppending on the application. 

My solution so far is:

```
if ARGV[0].split(':')[0] == 'api'
  require 'capistrano/bundler'
  require 'capistrano/rails'
  require 'capistrano/rails/migrations'
  require 'capistrano/puma'
  require 'capistrano/puma/workers'
  require 'capistrano/puma/jungle'
  require 'capistrano/puma/monit'
  require 'capistrano/puma/nginx'
elsif ARGV[0].split(':')[0] == 'web'

end
```

Any better ideas? 

If I put the requires inside the api/production.rb for example, I got other sort of weird errors.

**Comment by vnazarenko** [comment]
Agree, i have the same situation. My service contains from 3 different apps. And I use caphub to have all deployment in one place. But one application require sidekiq, and others not. So if i add 

``` ruby
  require 'capistrano/sidekiq'
  require 'capistrano/sidekiq/monit'
```

to Capfile, and try to deploy application without sidekiq, i get exception during deploy that app do not use sidekiq ( it try to call sidekiq callback on app with out sidekiq). So i tried to move that requirement to 
app deploy config ( like config/deploy/app/production.rb ) But then no callbacks for sidekiq called. 
So what is the best way to handle different app requirements in caphub

**Comment by le0pard** [comment]
@vnazarenko

``` ruby
set :sidekiq_default_hooks, -> { false }
```

where you no need hook sidekiq tasks. So it is not a problem.

**Comment by vnazarenko** [comment]
It could be done this way, but what should i do if one of application is static html and no need any rails hooks for it ( like for angular in Fabs example above)?

**Comment by le0pard** [comment]
@vnazarenko

``` ruby
set :migration_role, nil
set :assets_roles, []
```

For rails to prevent hooks. Need some bad plugin for such example.

**Comment by vnazarenko** [comment]
But it's some kind of 'hacky' workaround. What if i don't want to require not needed scripts for some apps, but other apps require them

**Comment by le0pard** [comment]
@vnazarenko it is how designed registration tasks and hooks in capistrano (by `Capfile`). Caphub just extend capistrano. So if you need change this approach - you need change it in capistrano.

**Comment by vnazarenko** [comment]
Ok, so @Fabs solutions is kind of best solutions/workarounds for now
