### ISSUE TITLE
Loading default bundler configurations

### ISSUE THREAD

**Issue by juanibiapina** [railsware/caphub#6]
After creating a fresh project and uncommenting the lines relative to capistrano-bundler, `bundle_roles` (and other bundler defaults) is not set. I need to set it manually or call load:defaults task.

This does not happen with plain capistrano.

**Comment by ayanko** [comment]
gem "capistrano-multiconfig", "3.0.4"

**Comment by juanibiapina** [comment]
You guys are fast.
